### ISSUE TITLE
Excuse me, why am I running wrong? Can you say a little more?

### ISSUE THREAD

**Issue by MMMbka789** [ronbadur/maven-artifacts-uploader#4]
`D:\Maven\nexus\maven-artifacts-uploader\bin>mvnUploader -d path D:\Maven\maven_repos_sms\com\alibaba
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initialization logging.
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.io.UncheckedIOException: there is problem with config.properties
  while locating apollo.modules.RepositoryIdProvider
  while locating java.lang.String annotated with @com.google.inject.name.Named(value=repositoryIdOption)
    for the 1st parameter of apollo.deploy_options.RepositoryIdOption.<init>(RepositoryIdOption.java:15)
  while locating apollo.deploy_options.RepositoryIdOption
    for the 3rd parameter of apollo.modules.MavenCommandsProvider.<init>(MavenCommandsProvider.java:22)
  while locating apollo.modules.MavenCommandsProvider
  while locating java.util.List<apollo.maven.MavenDeployOption>
    for the 1st parameter of apollo.maven.MavenCommandFactory.<init>(MavenCommandFactory.java:17)
  while locating apollo.maven.MavenCommandFactory
    for the 1st parameter of apollo.maven.MavenDeployer.<init>(MavenDeployer.java:21)
  while locating apollo.maven.MavenDeployer
    for the 2nd parameter of apollo.upload.MavenUploader.<init>(MavenUploader.java:30)
  while locating apollo.upload.MavenUploader
  while locating apollo.upload.Uploader
Caused by: java.io.UncheckedIOException: there is problem with config.properties
        at apollo.modules.RepositoryIdProvider.get(RepositoryIdProvider.java:29)
        at apollo.modules.RepositoryIdProvider.get(RepositoryIdProvider.java:14)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
        at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
        at apollo.command_line.Main.main(Main.java:31)
Caused by: java.nio.file.NoSuchFileException: D:\Maven\nexus\maven-artifacts-uploader\bin\conf\config.properties
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at java.nio.file.Files.newBufferedReader(Files.java:2784)
        at java.nio.file.Files.newBufferedReader(Files.java:2816)
        at apollo.modules.RepositoryIdProvider.get(RepositoryIdProvider.java:26)
        ... 37 more

2) Error in custom provider, java.io.UncheckedIOException: there is problem with config.properties file
  while locating apollo.modules.RepositoryUrlProvider
  while locating java.lang.String annotated with @com.google.inject.name.Named(value=urlOption)
    for the 1st parameter of apollo.deploy_options.UrlDeployOption.<init>(UrlDeployOption.java:15)
  while locating apollo.deploy_options.UrlDeployOption
    for the 4th parameter of apollo.modules.MavenCommandsProvider.<init>(MavenCommandsProvider.java:22)
  while locating apollo.modules.MavenCommandsProvider
  while locating java.util.List<apollo.maven.MavenDeployOption>
    for the 1st parameter of apollo.maven.MavenCommandFactory.<init>(MavenCommandFactory.java:17)
  while locating apollo.maven.MavenCommandFactory
    for the 1st parameter of apollo.maven.MavenDeployer.<init>(MavenDeployer.java:21)
  while locating apollo.maven.MavenDeployer
    for the 2nd parameter of apollo.upload.MavenUploader.<init>(MavenUploader.java:30)
  while locating apollo.upload.MavenUploader
  while locating apollo.upload.Uploader
Caused by: java.io.UncheckedIOException: there is problem with config.properties file
        at apollo.modules.RepositoryUrlProvider.get(RepositoryUrlProvider.java:26)
        at apollo.modules.RepositoryUrlProvider.get(RepositoryUrlProvider.java:11)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
        at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
        at apollo.command_line.Main.main(Main.java:31)
Caused by: java.nio.file.NoSuchFileException: D:\Maven\nexus\maven-artifacts-uploader\bin\conf\config.properties
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at java.nio.file.Files.newBufferedReader(Files.java:2784)
        at java.nio.file.Files.newBufferedReader(Files.java:2816)
        at apollo.modules.RepositoryUrlProvider.get(RepositoryUrlProvider.java:23)
        ... 37 more

2 errors
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
        at apollo.command_line.Main.main(Main.java:31)`

**Comment by kevlam2706** [comment]
I found this to be true as well. It seems to be looking for the configuration file under (in your case) D:\Maven\nexus\maven-artifacts-uploader\bin\conf\config.properties instead of D:\Maven\nexus\maven-artifacts-uploader\conf\config.properties.

I tried to work around it by copying the conf directory into the bin directory. The program then runs without error but outputs nothing, and appears to do nothing.

**Comment by ronbadur** [comment]
hey @greyingjay , make sure that you have the 'mvn' command in your path

**Comment by kevlam2706** [comment]
mvn is definitely on the path.

Is there a quick and easy way of enabling logging output without setting up log4j2?

**Comment by ronbadur** [comment]
I think the quick and the easy way to enable logging is to open the project with IDEA such as Intellij and run the 'Main' class with -d parameter
